### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by XxLuminousxX** [improvshark/docker-dontStarveTogether#1]
Help I can't join my server from the same computer I'm hosting it from
where it says

Note that if you will be playing Don't Starve Together from the same computer you are hosting the dedicated server on, you should use a different configuration directory for the dedicated server. This can be done by using the launch option "-conf_dir myDSTserver", which will change it to use this folder:
Documents/Klei/myDSTserver/
this was on the wiki

how do i do this it just says using the launch option where is that

**Comment by improvshark** [comment]
The launch option would be added into the Dockerfile on line 47, that is where the program is launched.

I don't think you would need to change the configuration directory for this particular setup though. Since it is running in docker it has its own directory that wont conflict with the clients. Did you add your server_token to the settings.ini file? (line 4). You should also forward ports so your server can be added to the global server list.

**Comment by XxLuminousxX** [comment]
I got it I figured it out
